### ISSUE TITLE
Can't connect to MQTT broker

### ISSUE THREAD

**Issue by Calimerorulez** [git-developer/tfrec-mqtt#2]
Hi,

I just discovered this repo and want to use it with my sensors, but I have a hard time connecting to my MQTT broker. I've created a user and password, and I'm using the following parameters for MQTT_OPTIONS in the environment variables in the container, but it does not connect:

`-h 192.168.5.110 -u tfrec -P tfrec -p 1883`

Is there something I'm doing wrong?

**Comment by git-developer** [comment]
Does the broker run in a container on the same host (cf. [Connection issues](https://github.com/git-developer/tvheadend-mqtt#connection-issues))?

**Comment by git-developer** [comment]
You can check if the broker is reachable from the container by running
```console
$ docker run --rm -ti ckware/tfrec-mqtt ping 192.168.5.110
```

**Comment by git-developer** [comment]
Does the issue still occur, @Calimerorulez?

**Comment by Calimerorulez** [comment]
Hi @git-developer,

Sorry for my late reply, I'm having a short vacation. I will try again this Friday, when I get back home.

**Comment by Calimerorulez** [comment]
Hi,

I'm closing the issue, because now I even can't connect to my RTL-stick anymore since I came back. Sorry for my confusion :(

**Comment by git-developer** [comment]
No problem. Feel free to re-open this issue or open a new one when you find a reproduceable problem.
